name: Build LX Images
on:
    push:
        branches:
            - master
jobs:
    prepare:
        name: Create Release ${{ github.ref }}
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            tag: ${{ steps.timestamp.outputs.tag }}
        steps:
            - name: Create Time Stamp Tag
              id: tag
              run: date +'::set-output name=tag::%Y-%m-%d_%H-%M-%S'
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.tag.outputs.tag }}
                  release_name: Release ${{ steps.tag.outputs.tag }}
                  draft: false
                  prerelease: false
    ubuntu:
        needs: prepare
        strategy:
            matrix:
                RELEASE:
                    - 20.04
                    - 18.04
        
        name: Build Ubuntu ${{ matrix.RELEASE }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Image
              id: build_image
              run: |
                cd ubuntu
                tar=lx-ubuntu-${{ matrix.RELEASE }}.tar
                tag=release:$$
                docker build . -t $tag --build-arg release=${{ matrix.RELEASE }}
                container=$(docker create $tag)
                docker  cp $container:/ - > $tar
                docker rm $container
                docker rmi $tag
                xz $tar
            - name: Upload Release Asset
              id: upload_release_asset 
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }} 
                  asset_path: ./ubuntu/lx-ubuntu-${{ matrix.RELEASE }}.tar.xz
                  asset_name: lx-ubuntu-${{ matrix.RELEASE }}-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-tar